### PR TITLE
the width of the button is too small

### PR DESCRIPTION
**Pull request by amarradi**
I changed the hardcoded value of the width to wrap_content. Now it fits at least for the german language

### CODE REVIEW

**Review by CrazyMarvin — APPROVED** [review]
Thanks 👍

**Comment by amarradi** [comment]
I'm the big developer now, I'm just starting to program. So I'm trying to learn to pushing my first app a bit.
I was looking for an app that would count the days since or up to a certain time. That's when VacationDays came to my attention.

**Comment by CrazyMarvin** [comment]
Nice, that's great! 😎

**Comment by CrazyMarvin** [comment]
#63 fixed

**Pull request merged**
