### PR TITLE
fixing CI

### PR DESCRIPTION
**Pull request by tharun634**
fixed the CI to create coverage

### CODE REVIEW

**Comment by tharun634** [comment]
@arafaatqureshi @CrazyMarvin there are some failing tests, can you please resolve them.

Logs from my fork:
https://github.com/tharun634/VacationDays/runs/5528596666?check_suite_focus=true#step:8:47

**Comment by CrazyMarvin** [comment]
> @arafaatqureshi @CrazyMarvin there are some failing tests, can you please resolve them.
> 
> Logs from my fork:
> https://github.com/tharun634/VacationDays/runs/5528596666?check_suite_focus=true#step:8:47

Can we access the test report from GitHub Actions?

**Comment by tharun634** [comment]
> Can we access the test report from GitHub Actions?

I am afraid not. But you can replicate the same by just cloning my fork locally and running `./gradlew clean jacocoTestReport`. 
I currently do not have an Android dev setup on my workstation. if not, I would've ran it myself 😓

**Comment by CrazyMarvin** [comment]
FYI @tharun634, we reverted your changes in the app/build.gradle back due to some build issues/warnings but we will try to add the JaCoCo stuff again this week.
The lint issues should be "fixed".

**Pull request merged**
