### PR TITLE
Implement backup and restore without storage permission

### LINKED ISSUE #29: Use of All files access (MANAGE_EXTERNAL_STORAGE) permission
The app offers a backup feature. Is there an option to save it on the device and keep it after uninstalling the backup without using this [permission](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en&visit_id=637827227701244456-1173491181&rd=1)?

### PR DESCRIPTION
**Pull request by unbiaseduser**
Hello. So, I have seen that this app advertises backup/restore feature but that functionality is missing in the actual app. Thus, I decided to look around in the code and I found out that the backup/restore code was actually present, but it seems to be tied to the storage permission. I have ported the code to use the `ActivityResultContracts` API, which requires no permission. I hope you can take a look at it.

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
That's awesome, @unbiaseduser! Thank you very much.
Please check if we can merge it, @arafaatqureshi.

**Comment by arafaatqureshi** [comment]
@unbiaseduser  Thank you so much for your input, i was still working with the same issue. Highly appreciated. 
Let me go through your code, will merge it after that :)

**Comment by unbiaseduser** [comment]
@arafaatqureshi Any progress so far? This is taking a bit too long for a simple change.
Keep in mind that it is you who wrote the main backup/restore code and I just adapted it a little bit.
I really don't think that it should take _**days**_ for you to review...

**Review by arafaatqureshi — APPROVED** [review]

**Comment by unbiaseduser** [comment]
Oh thank you, good sir. I was worrying you would be inactive.

**Pull request merged**
